name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Cache dependencies
        id: cache-lint
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.lint.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.lint.txt
      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: ci_pass
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -d test_db -U github"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis-primary:
        image: redis/redis-stack-server:7.0.0-RC5
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis-celery:
        image: redis/redis-stack-server:7.0.0-RC5
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Cache dependencies
        id: cache-test
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.test.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/requirements.test.txt
      - name: Run tests
        run: |
          export PYTHONUNBUFFERED=1
          export NN_DEBUG=1
          export NN_PROJECT_BASE_URL=http://api-notifications.localhost:8011
          export NN_SERVER_PORT=8004
          export NN_PROJECT_NAME=netflix-notifications
          export NN_API_V1_STR=/api/v1
          export NN_SERVER_NAME=localhost
          export NN_SERVER_HOSTS=http://api-notifications.localhost:8011
          export NAA_SECRET_KEY=changeme
          export NN_DB_HOST=localhost
          export NN_DB_PORT=5432
          export NN_DB_NAME=test_db
          export NN_DB_USER=github
          export NN_DB_PASSWORD=ci_pass
          export NN_REDIS_DECODE_RESPONSES=1
          export NN_REDIS_PORT=6379
          export NN_REDIS_URL=redis://localhost:6379/0
          export NN_REDIS_OM_URL=redis://@localhost:6379
          export NN_CELERY_BROKER_URL=redis://localhost:6380/0
          export NN_CELERY_RESULT_BACKEND=redis://localhost:6380/0
          export NN_FLOWER_PORT=8888
          export NN_USE_STUBS=1
          export NN_TESTING=1
          export NN_CI=1
          export PYTEST_ADDOPTS="--ignore-glob=tests/functional/*"
          make test

  build-and-push-image:
    needs: [ lint, test ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            dockerfile: ./dev.Dockerfile
            image: yandexmiddleteamv1/netflix-notifications
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
